name: "Dashy"
description: "Dashy integration for Home Assistant"
version: "0.2"
slug: "dashy_addon"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8080/tcp: 8080
map:
  - share:rw
